// apps/web-repl/src/App.tsx
import styles from './App.module.css'
import { useAction } from '@reatom/npm-react'
import { useEffect } from 'react'
import { onError, onResult, onWorkerReady } from './atoms'
import { Toolbar } from './Toolbar'
import { compilerWorker } from './workerInstance'
import { CodeEditor } from './CodeEditor'
import { RunResult } from './RunResult'

export function App() {
  const handleWorkerReady = useAction(onWorkerReady)
  const handleResult = useAction(onResult)
  const handleError = useAction(onError)

  useEffect(() => {
    const handleMessage = (event: MessageEvent) => {
      const { type, result, error } = event.data

      if (type === 'ready') {
        handleWorkerReady()
      } else if (type === 'result') {
        handleResult(result)
      } else if (type === 'error') {
        handleError(error)
      }
    }

    compilerWorker.addEventListener('message', handleMessage)
    return () => compilerWorker.removeEventListener('message', handleMessage)
  }, [])

  return (
    <div className={styles.app}>
      <Toolbar />
      <main className={styles.main}>
        <CodeEditor />
        <RunResult />
      </main>
    </div>
  )
}

// apps/web-repl/src/App.vue
<script setup lang="ts">
import { onMounted } from 'vue'
import CodeEditor from './components/CodeEditor.vue'
import RunResult from './components/RunResult.vue'
import Toolbar from './components/Toolbar.vue'
import { useCodeStore } from './stores/useCodeStore.ts'
import { compilerWorker } from './workerInstance.ts'

const codeStore = useCodeStore()

onMounted(() => {
  const handleMessage = (event: MessageEvent) => {
    const { type, result, error } = event.data

    if (type === 'ready') {
      codeStore.setWorkerReady()
    } else if (type === 'result') {
      codeStore.setResult(result)
    } else if (type === 'error') {
      codeStore.setError(error)
    }
  }

  compilerWorker.addEventListener('message', handleMessage)
})
</script>

<template>
  <UApp>
    <div class="app">
      <Toolbar />

      <main class="main">
        <CodeEditor />
        <RunResult />
      </main>
    </div>
  </UApp>
</template>

<style scoped>
.app {
  width: 100%;
  height: 100vh;
  display: flex;
  flex-direction: column;
}

.main {
  display: flex;
  width: 100%;
  flex: 1;
  min-height: 0;
}
</style>
