// apps/web-repl/src/components/Toolbar.vue
<script setup lang="ts">
import { CODE_EXAMPLES } from './codeExamples'
import ThemeButton from './ThemeButton.vue'
import { useCodeStore, type Mode } from '@/stores/useCodeStore.ts'
import type { DropdownMenuItem } from '@nuxt/ui'

const codeStore = useCodeStore()

const radioItems: Array<{ label: string; value: Mode }> = [
  { label: 'Compiler', value: 'compiler' },
  { label: 'Interpreter', value: 'interpreter' },
]

const codeExampleItems: DropdownMenuItem[] = CODE_EXAMPLES.map(example => ({
  label: example.label,
  onSelect: () => codeStore.changeCodeExample(example.value),
}))
</script>

<template>
  <header class="header">
    <div class="toolbar">
      <div />

      <div class="centerToolbar">
        <UDropdownMenu :items="codeExampleItems">
          <UButton
            label="Code examples"
            trailing-icon="i-lucide-chevron-down"
            color="neutral"
            variant="outline" />
        </UDropdownMenu>

        <UButton
          @click="codeStore.runCode()"
          :loading="codeStore.isLoading"
          :disabled="!codeStore.code">
          Run
        </UButton>

        <URadioGroup v-model="codeStore.runnerMode" :items="radioItems" orientation="horizontal" />
      </div>

      <ThemeButton />
    </div>
  </header>
</template>

<style lang="css" scoped>
.header {
  height: 60px;
  border-bottom: 1px solid var(--ui-border);
}

.toolbar {
  display: flex;
  align-items: center;
  justify-content: space-between;
  flex-wrap: wrap;
  gap: 0.5rem;
  height: 100%;
  padding: 0.5rem;
}

.centerToolbar {
  display: flex;
  height: 100%;
  align-items: center;
  gap: 0.5rem;
}

.codeExamplesSelect {
  width: 160px;
}
</style>

// apps/web-repl/src/Toolbar.tsx
import {
  ActionIcon,
  Button,
  Flex,
  Group,
  Radio,
  Select,
  useMantineColorScheme,
} from '@mantine/core'
import { useAction, useAtom } from '@reatom/npm-react'

import styles from './App.module.css'
import {
  runnerModeAtom,
  runCode,
  onRunnerModeChange,
  type Mode,
  isLoadingAtom,
  onChangeCodeExample,
} from './atoms'
import { CODE_EXAMPLES } from './codeExamples'
import { IconSun, IconSunOff } from '@tabler/icons-react'

export const Toolbar = () => {
  const [runnerMode] = useAtom(runnerModeAtom)
  const [isLoading] = useAtom(isLoadingAtom)

  const run = useAction(runCode)
  const changeRunnerMode = useAction(onRunnerModeChange)
  const changeExample = useAction(onChangeCodeExample)

  return (
    <header className={styles.header}>
      <Flex px="lg" h="100%" w="100%" align="center" justify="space-between">
        <div />
        <Flex h="100%" align="center" gap="lg">
          <Select
            data={CODE_EXAMPLES}
            placeholder="Code examples"
            value={null}
            defaultValue=""
            style={{ width: '160px' }}
            onChange={value => {
              if (value) {
                changeExample(value)
              }
            }}
          />

          <Button onClick={run} loading={isLoading}>
            Run
          </Button>

          <Radio.Group value={runnerMode} onChange={value => changeRunnerMode(value as Mode)}>
            <Group>
              <Radio value="compiler" label="Compiler" />
              <Radio value="interpreter" label="Interpreter" />
            </Group>
          </Radio.Group>
        </Flex>

        <ThemeButton />
      </Flex>
    </header>
  )
}

const ThemeButton = () => {
  const { colorScheme, toggleColorScheme } = useMantineColorScheme()

  return (
    <ActionIcon onClick={toggleColorScheme} variant="transparent">
      {colorScheme === 'light' ? <IconSunOff /> : <IconSun />}
    </ActionIcon>
  )
}
